# # FedPylot by Cyprien Quéméneur, GPL-3.0 license

# import argparse
# import os
# import shutil
# import sys
# sys.path.append('yolov7')

# # from mpi4py import MPI
# from mpi4py import MPI
# import pandas as pd
# import yaml

# from node import Client, Node, Server


# def init_node(rank: int, server_opt: str, server_lr: float, tau: float, beta: float) -> Node:
#     """Initialize a node (client or server) based on its rank."""
#     available_optimizers = ['fedavg', 'fedavgm', 'fedadagrad', 'fedadam', 'fedyogi']
#     if server_opt not in available_optimizers:
#         raise ValueError(f'Server optimizer {server_opt} unavailable, must be in {available_optimizers}.')
#     return Server(server_opt, server_lr, tau, beta) if rank == 0 else Client(rank)


# def share_public_keys(node: Node) -> None:
#     """Clients receive the server's public key while the server receives each client's public key."""
#     key_rank_pairs = comm.gather((node.rank, node.public_key), root=0)
#     if node.rank == 0:
#         key_rank_pairs = {r: cpk for r, cpk in key_rank_pairs}
#         key_rank_pairs.pop(0)
#         node.clients_public_keys = key_rank_pairs
#     public_key = comm.bcast(node.public_key, root=0)
#     if node.rank != 0:
#         node.server_public_key = public_key


# def share_symmetric_key(node: Node) -> None:
#     """The symmetric key is generated by the server and shared among the clients using asymmetric encryption."""
#     if node.rank == 0:
#         node.generate_symmetric_key()
#         sk = [None] + node.get_symmetric_key()
#     else:
#         sk = None
#     sk = comm.scatter(sk, root=0)
#     if node.rank != 0:
#         node.symmetric_key = sk


# def initial_broadcast(node: Node, pretrained_weights: str, data: str, cfg: str, hyp: str, imgsz: int) -> None:
#     """The central server initializes the checkpoint from a pretrained weights file and shares it with the clients."""
#     if node.rank == 0:
#         node.initialize_model(pretrained_weights)
#         encrypted_data = [None] + node.get_weights(metadata=True)
#         node.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)
#     else:
#         encrypted_data = None
#     encrypted_data = comm.scatter(encrypted_data, root=0)
#     if node.rank != 0:
#         node.set_weights(encrypted_data, metadata=True)


# def federated_loop(node: Node, nrounds: int, epochs: int, saving_path: str, architecture: str, pretrained_weights: str,
#                    data: str, bsz_train: int, bsz_val: int, imgsz: int, conf_thres: float, iou_thres: float, cfg: str,
#                    hyp: str, workers: int) -> None:
#     """Orchestrate the federated learning experiment."""
#     for kround in range(nrounds):
#         # At the beginning of a round, generate and share a new symmetric key
#         share_symmetric_key(node)
#         # If it is the first round, the central server sends the initial checkpoint to the clients
#         if kround == 0:
#             initial_broadcast(node, pretrained_weights, data, cfg, hyp, imgsz)
#         # Client level computation (local training)
#         if node.rank != 0:
#             node.train(nrounds, kround, epochs, architecture, data, bsz_train, imgsz, cfg, hyp, workers, saving_path)
#             sd_encrypted = node.get_update()
#         else:
#             sd_encrypted = None
#         # Updates are gathered by the central server
#         sd_encrypted = comm.gather(sd_encrypted, root=0)
#         # Server level computation (server optimization, re-parameterization, and evaluation on the validation set)
#         if node.rank == 0:
#             for i, item in enumerate(sd_encrypted):
#                 print(f"[Server] Received update from rank {i}: {type(item)}")
#             sd_encrypted.pop(0)
#             node.aggregate(sd_encrypted)
#             node.reparameterize(architecture)
#             node.test(kround, saving_path, data, bsz_val, imgsz, conf_thres, iou_thres)
#             sd_encrypted = [None] + node.get_weights(metadata=False)
#         else:
#             sd_encrypted = None
#         # New weights are shared with the clients
#         sd_encrypted = comm.scatter(sd_encrypted, root=0)
#         if node.rank != 0:
#             node.set_weights(sd_encrypted, metadata=False)


# def gather_analytics(saving_path: str, node: Node) -> None:
#     """Gather local analytics from the client nodes' local storage back to the server's local storage."""
#     os.makedirs(f'{saving_path}/run/local-analytics/')
#     if node.rank != 0:
#         df_lr = pd.read_csv(f'{saving_path}/run/train-client{node.rank}/optim_params.csv')
#         df_loss = pd.read_csv(f'{saving_path}/run/train-client{node.rank}/training_losses.csv')
#         with open(f'{saving_path}/run/train-client{node.rank}/opt.yaml') as f:
#             save_yaml = yaml.load(f, Loader=yaml.SafeLoader)
#         local_analytics = (df_lr, df_loss, save_yaml)
#     else:
#         local_analytics = None, None, None
#     local_analytics = comm.gather(local_analytics, root=0)
#     if node.rank == 0:
#         for i, (df_lr, df_loss, save_yaml) in enumerate(local_analytics):
#             if i != 0:
#                 df_lr.to_csv(f'{saving_path}/run/local-analytics/optim_params_{i}.csv')
#                 df_loss.to_csv(f'{saving_path}/run/local-analytics/training_losses_{i}.csv')
#                 with open(f'{saving_path}/run/local-analytics/opt_{i}.yaml', 'w') as f:
#                     yaml.dump(save_yaml, f)

# def local_federated_loop(n_clients: int, nrounds: int, epochs: int, saving_path: str,
#                          architecture: str, pretrained_weights: str, data: str,
#                          bsz_train: int, bsz_val: int, imgsz: int, conf_thres: float,
#                          iou_thres: float, cfg: str, hyp: str, workers: int,
#                          server_opt: str, server_lr: float, tau: float, beta: float):

#     # 1️⃣ Khởi tạo server và các client
#     server = Server(server_opt, server_lr, tau, beta)
#     clients = [Client(rank=i+1) for i in range(n_clients)]

#     print(f"[Setup] Initialized {n_clients} clients and 1 server.")

#     # 2️⃣ Server gửi model khởi tạo
#     server.initialize_model(pretrained_weights)
#     weights = server.get_weights(metadata=True)

#     for c in clients:
#         c.set_weights(weights, metadata=True)
#         c.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)

#     # 3️⃣ Vòng lặp federated learning
#     for kround in range(nrounds):
#         print(f"\n====== Round {kround+1}/{nrounds} ======")

#         updates = []
#         for i, client in enumerate(clients, 1):
#             print(f"\n[Client {i}] Local training...")
#             client.train(nrounds, kround, epochs, architecture, data, bsz_train, imgsz, cfg, hyp, workers, saving_path)
#             updates.append(client.get_update())

#         print("\n[Server] Aggregating updates...")
#         server.aggregate(updates)
#         server.reparameterize(architecture)
#         server.test(kround, saving_path, data, bsz_val, imgsz, conf_thres, iou_thres)

#         # Broadcast new weights
#         new_weights = server.get_weights(metadata=False)
#         for c in clients:
#             c.set_weights(new_weights, metadata=False)

#     print("\n✅ Federated training finished successfully.")


# def federated_secure_loop(num_clients, nrounds, epochs, saving_path,
#                           architecture, pretrained_weights, data,
#                           bsz_train, bsz_val, imgsz, conf_thres,
#                           iou_thres, cfg, hyp, workers):
#     """
#     Mô phỏng Federated Learning có mã hóa nhưng chạy tuần tự trên Kaggle.
#     Giữ nguyên cơ chế mã hóa của FedPylot (public/private/symmetric).
#     """

#     # ===== 1. Tạo server và client =====
#     print("🚀 Initializing Server and Clients...")
#     server = Server(server_opt='fedavg', serverlr=1.0, tau=1e-3, beta=0.1)
#     clients = [Client(rank=i + 1) for i in range(num_clients)]

#     # ===== 2. Trao đổi public keys =====
#     print("🔐 Exchanging public keys...")
#     for client in clients:
#         client.server_public_key = server.public_key
#     server.clients_public_keys = {client.rank: client.public_key for client in clients}

#     # ===== 3. Server khởi tạo model và symmetric key =====
#     print("🧠 Initializing model and symmetric keys...")
#     server.initialize_model(pretrained_weights)
#     server.generate_symmetric_key()

#     # symmetric_keys: list[encrypted_symmetric_key_for_each_client]
#     symmetric_keys = server.get_symmetric_key()

#     # ===== 4. Mỗi client nhận symmetric key và model khởi tạo =====
#     print("📦 Distributing initial model to clients...")
#     encrypted_models = server.get_weights(metadata=True)
#     for i, client in enumerate(clients):
#         client.symmetric_key = symmetric_keys[i]   # key riêng cho client i
#         client.set_weights(encrypted_models[i], metadata=True)
#         client.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)

#     # ===== 5. Vòng lặp Federated Learning =====
#     for rnd in range(nrounds):
#         print(f"\n🌐 ROUND {rnd + 1}/{nrounds}")
#         encrypted_updates = []

#         # --- Clients: local training ---
#         for client in clients:
#             print(f"🏋️ Client {client.rank} training locally...")
#             client.train(nrounds, rnd, epochs, architecture, data,
#                          bsz_train, imgsz, cfg, hyp, workers, saving_path)
#             update = client.get_update()  # encrypted gradient/update
#             encrypted_updates.append(update)

#         # --- Server: aggregate + reparameterize ---
#         print("🖥️ Server aggregating encrypted updates...")
#         server.aggregate(encrypted_updates)
#         server.reparameterize(architecture)

#         # --- Server: evaluate on validation set ---
#         server.test(rnd, saving_path, data, bsz_val, imgsz, conf_thres, iou_thres)

#         # --- Server gửi model mới cho các client ---
#         print("📤 Broadcasting new global weights to clients...")
#         new_encrypted_weights = server.get_weights(metadata=False)
#         for client in clients:
#             client.set_weights(new_encrypted_weights, metadata=False)

#     print("\n✅ Secure Federated Learning simulation completed successfully!")



# # if __name__ == "__main__":
# #     parser = argparse.ArgumentParser()
# #     parser.add_argument('--nrounds', type=int, default=3)
# #     parser.add_argument('--epochs', type=int, default=1)
# #     parser.add_argument('--nclients', type=int, default=2, help='number of simulated clients')
# #     parser.add_argument('--server-opt', type=str, default='fedavg')
# #     parser.add_argument('--server-lr', type=float, default=1.)
# #     parser.add_argument('--tau', type=float, default=1e-3)
# #     parser.add_argument('--beta', type=float, default=0.1)
# #     parser.add_argument('--architecture', type=str, default='yolov7')
# #     parser.add_argument('--weights', type=str, help='path to pretrained weights')
# #     parser.add_argument('--data', type=str, help='*.data path')
# #     parser.add_argument('--bsz-train', type=int, default=16)
# #     parser.add_argument('--bsz-val', type=int, default=16)
# #     parser.add_argument('--img', type=int, default=640)
# #     parser.add_argument('--conf', type=float, default=0.001)
# #     parser.add_argument('--iou', type=float, default=0.65)
# #     parser.add_argument('--cfg', type=str, default='yolov7/cfg/training/yolov7.yaml')
# #     parser.add_argument('--hyp', type=str)
# #     parser.add_argument('--workers', type=int, default=4)
# #     args = parser.parse_args()

# #     saving_path = 'experiments'
# #     os.makedirs(f"{saving_path}/weights", exist_ok=True)
# #     os.makedirs(f"{saving_path}/run", exist_ok=True)

# #     federated_secure_loop(
# #         num_clients=args.nclients,
# #         nrounds=args.nrounds,
# #         epochs=args.epochs,
# #         saving_path=saving_path,
# #         architecture=args.architecture,
# #         pretrained_weights=args.weights,
# #         data=args.data,
# #         bsz_train=args.bsz_train,
# #         bsz_val=args.bsz_val,
# #         imgsz=args.img,
# #         conf_thres=args.conf,
# #         iou_thres=args.iou,
# #         cfg=args.cfg,
# #         hyp=args.hyp,
# #         workers=args.workers,
# #     )


# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--nrounds', type=int, default=30, help='number of communication rounds')
#     parser.add_argument('--epochs', type=int, default=5, help='number of epochs executed per communication round')
#     parser.add_argument('--server-opt', type=str, default='fedavg', help='aggregation algorithm/server-side optimizer')
#     parser.add_argument('--server-lr', type=float, default=1., help='server learning rate')
#     parser.add_argument('--tau', type=float, default=1e-3, help='server adaptivity for FedAdagrad, FedAdam and FedYogi')
#     parser.add_argument('--beta', type=float, default=0.1, help='server momentum with FedAvgM')
#     parser.add_argument('--architecture', type=str, default='yolov7', help='model architecture')
#     parser.add_argument('--weights', type=str, help='path to pretrained weights')
#     parser.add_argument('--data', type=str, help='*.data path')
#     parser.add_argument('--bsz-train', type=int, default=32, help='batch size used for training')
#     parser.add_argument('--bsz-val', type=int, default=32, help='batch size used for evaluation')
#     parser.add_argument('--img', type=int, default=640, help='inference size (pixels)')
#     parser.add_argument('--conf', type=float, default=0.001, help='object confidence threshold')
#     parser.add_argument('--iou', type=float, default=0.65, help='IOU threshold for NMS')
#     parser.add_argument('--cfg', type=str, default='yolov7/cfg/training/yolov7.yaml', help='model.yaml path')
#     parser.add_argument('--hyp', type=str, help='hyperparameters path, also decides client-side optimizer')
#     parser.add_argument('--workers', type=int, default=8, help='number of workers to use during training')
#     args = parser.parse_args()

#     # Initialize MPI
#     comm = MPI.COMM_WORLD
#     rank = comm.Get_rank()
#     node = init_node(rank, args.server_opt, args.server_lr, args.tau, args.beta)
#     node.get_device_info()

#     # Save the number of training examples held by the clients to perform weighted average aggregation of the updates
#     with open(args.data) as f:
#         if node.rank != 0:
#             img_path = os.path.join(yaml.load(f, Loader=yaml.SafeLoader)['train'], f'client{node.rank}', 'images')
#             node.nsamples = len(os.listdir(img_path))

#     # The clients exchange their public keys with the central server and vice-versa
#     share_public_keys(node)

#     # Create saving folder
#     saving_path = 'experiments'
#     os.makedirs(saving_path)
#     os.makedirs(saving_path + '/weights/')
#     os.makedirs(saving_path + '/run/')

#     # Save config, cfg, hyp and data files
#     if node.rank == 0:
#         with open(saving_path + '/config.txt', 'w') as f:
#             f.write(f'nrounds: {args.nrounds}\n')
#             f.write(f'epochs: {args.epochs}\n')
#             f.write(f'server opt: {args.server_opt}\n')
#             f.write(f'server learning rate: {args.server_lr}\n')
#             if args.server_opt == 'fedavgm':
#                 f.write(f'fedavgm - beta: {args.beta}\n')
#             if args.server_opt == 'fedadagrad':
#                 f.write(f'fedadagrad - tau: {args.tau}\n')
#             if args.server_opt in ['fedadam', 'fedyogi']:
#                 f.write(f'{args.server_opt} - tau: {args.tau}\n')
#                 f.write(f'{args.server_opt} - beta1: {0.9}\n')
#                 f.write(f'{args.server_opt} - beta2: {0.99}\n')
#             f.write(f'architecture: {args.architecture}\n')
#             f.write(f'weights: {args.weights}\n')
#             f.write(f'data: {args.data}\n')
#             f.write(f'batch size (train): {args.bsz_train}\n')
#             f.write(f'batch size (eval): {args.bsz_val}\n')
#             f.write(f'img: {args.img}\n')
#             f.write(f'conf: {args.conf}\n')
#             f.write(f'iou: {args.iou}\n')
#             f.write(f'cfg: {args.cfg}\n')
#             f.write(f'hyp: {args.hyp}\n')
#             f.write(f'workers: {args.workers}\n')
#         shutil.copy(args.cfg, saving_path)
#         shutil.copy(args.hyp, saving_path)
#         shutil.copy(args.data, saving_path)

#     # Launch federated learning experiment
#     federated_loop(
#         node=node,
#         nrounds=args.nrounds,
#         epochs=args.epochs,
#         saving_path=saving_path,
#         architecture=args.architecture,
#         pretrained_weights=args.weights,
#         data=args.data,
#         bsz_train=args.bsz_train,
#         bsz_val=args.bsz_val,
#         imgsz=args.img,
#         conf_thres=args.conf,
#         iou_thres=args.iou,
#         cfg=args.cfg,
#         hyp=args.hyp,
#         workers=args.workers
#     )

#     # Gather clients' local analytics back to the orchestrating node in order to back up the files
#     gather_analytics(saving_path, node)




# import logging
# import time
# import argparse
# import os
# import shutil
# import sys
# sys.path.append('yolov7')

# import pandas as pd
# import yaml

# from node import Client, Server


# def federated_loop(server: Server, clients: list, nrounds: int, epochs: int, 
#                    saving_path: str, architecture: str, pretrained_weights: str, 
#                    data: str, bsz_train: int, bsz_val: int, imgsz: int, 
#                    conf_thres: float, iou_thres: float, cfg: str, hyp: str, 
#                    workers: int) -> None:
    
#     # === ĐĂNG KÝ CLIENTS VÀO OORT ===
#     if server.use_oort:
#         for client in clients:
#             server.oort_sampler.register_client(
#                 client.rank,
#                 client.nsamples,
#                 duration=1.0  # Initial estimate
#             )
#     # === END ===
    
#     # Server initializes model
#     print("Initializing model on server...")
#     server.initialize_model(pretrained_weights)
#     server.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)
    
#     for kround in range(nrounds):
#         print(f"\n{'='*50}")
#         print(f"Round {kround + 1}/{nrounds}")
#         print(f"{'='*50}")
        
#         if kround == 0:
#             initial_weights = server.get_weights(metadata=True)
#             for client in clients:
#                 client.set_weights(initial_weights, metadata=True)
#                 client.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)
        
#         # === CHỌN CLIENTS BẰNG OORT ===
#         if server.use_oort and kround > 0:  # Skip round 0
#             feasible = [c.rank for c in clients]
#             selected_ranks = server.oort_sampler.select_clients(
#                 num_clients=len(clients),
#                 feasible_clients=feasible,
#                 round_num=kround
#             )
#             active_clients = [c for c in clients if c.rank in selected_ranks]
#             print(f"[Oort] Selected {len(active_clients)}/{len(clients)} clients")
#         else:
#             active_clients = clients
#         # === END ===
        
#         updates = []
#         nsamples_list = []
        
#         import time
#         for client in active_clients:
#             print(f"\n--- Training Client {client.rank} ---")
#             train_start = time.time()
            
#             client.train(...)
            
#             train_duration = time.time() - train_start
#             update = client.get_update()
#             updates.append(update)
#             nsamples_list.append(client.nsamples)
            
#             # === CẬP NHẬT OORT STATS ===
#             if server.use_oort and kround > 0:
#                 # Assume loss is stored somewhere during training
#                 client_loss = 0.5  # Placeholder - get from actual training
#                 server.oort_sampler.update_client(
#                     client.rank,
#                     loss=client_loss,
#                     duration=train_duration,
#                     round_num=kround
#                 )
#             # === END ===
        
#         # Server aggregation
#         print(f"\n--- Server Aggregation ---")
#         server.aggregate(updates, nsamples_list)
#         server.reparameterize(architecture)
        
#         # Server evaluation
#         print(f"\n--- Server Evaluation ---")
#         server.test(kround, saving_path, data, bsz_val, imgsz, conf_thres, iou_thres)
        
#         # Broadcast new weights
#         new_weights = server.get_weights(metadata=False)
#         for client in clients:
#             client.set_weights(new_weights, metadata=False)


# def gather_analytics(saving_path: str, clients: list) -> None:
#     """Gather local analytics from clients."""
#     os.makedirs(f'{saving_path}/run/local-analytics/', exist_ok=True)
    
#     for client in clients:
#         rank = client.rank
#         try:
#             df_lr = pd.read_csv(f'{saving_path}/run/train-client{rank}/optim_params.csv')
#             df_loss = pd.read_csv(f'{saving_path}/run/train-client{rank}/training_losses.csv')
            
#             df_lr.to_csv(f'{saving_path}/run/local-analytics/optim_params_{rank}.csv', index=False)
#             df_loss.to_csv(f'{saving_path}/run/local-analytics/training_losses_{rank}.csv', index=False)
            
#             if os.path.exists(f'{saving_path}/run/train-client{rank}/opt.yaml'):
#                 with open(f'{saving_path}/run/train-client{rank}/opt.yaml') as f:
#                     save_yaml = yaml.load(f, Loader=yaml.SafeLoader)
#                 with open(f'{saving_path}/run/local-analytics/opt_{rank}.yaml', 'w') as f:
#                     yaml.dump(save_yaml, f)
#         except Exception as e:
#             print(f"Warning: Could not gather analytics for client {rank}: {e}")

# # def gather_analytics(saving_path: str, clients: list, server=None) -> None:
# #     """Gather local analytics from clients and optionally Oort utilities."""
# #     os.makedirs(f'{saving_path}/run/local-analytics/', exist_ok=True)
    
# #     for client in clients:
# #         rank = client.rank
# #         try:
# #             df_lr = pd.read_csv(f'{saving_path}/run/train-client{rank}/optim_params.csv')
# #             df_loss = pd.read_csv(f'{saving_path}/run/train-client{rank}/training_losses.csv')
            
# #             df_lr.to_csv(f'{saving_path}/run/local-analytics/optim_params_{rank}.csv', index=False)
# #             df_loss.to_csv(f'{saving_path}/run/local-analytics/training_losses_{rank}.csv', index=False)
            
# #             if os.path.exists(f'{saving_path}/run/train-client{rank}/opt.yaml'):
# #                 with open(f'{saving_path}/run/train-client{rank}/opt.yaml') as f:
# #                     save_yaml = yaml.load(f, Loader=yaml.SafeLoader)
# #                 with open(f'{saving_path}/run/local-analytics/opt_{rank}.yaml', 'w') as f:
# #                     yaml.dump(save_yaml, f)
# #         except Exception as e:
# #             print(f"Warning: Could not gather analytics for client {rank}: {e}")
    
# #     # Lưu utility nếu server và Oort có
# #     if server is not None and server.use_oort and hasattr(server, 'oort_sampler'):
# #         try:
# #             utilities = {}
# #             for client_id, info in server.oort_sampler.selector.totalArms.items():
# #                 utilities[client_id] = {
# #                     'reward': info['reward'],
# #                     'duration': info['duration'],
# #                     'count': info['count'],
# #                     'last_selected_round': info['time_stamp']
# #                 }
# #             df_util = pd.DataFrame.from_dict(utilities, orient='index')
# #             df_util.to_csv(f'{saving_path}/run/local-analytics/oort_utilities.csv')
# #             print(f"[INFO] Oort utilities saved for {len(utilities)} clients.")
# #         except Exception as e:
# #             print(f"Warning: Could not gather Oort utilities: {e}")



# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--nrounds', type=int, default=30, help='number of communication rounds')
#     parser.add_argument('--epochs', type=int, default=5, help='number of epochs per round')
#     parser.add_argument('--nclients', type=int, default=3, help='number of clients')
#     parser.add_argument('--server-opt', type=str, default='fedavg', help='aggregation algorithm')
#     parser.add_argument('--server-lr', type=float, default=1., help='server learning rate')
#     parser.add_argument('--tau', type=float, default=1e-3, help='server adaptivity')
#     parser.add_argument('--beta', type=float, default=0.1, help='server momentum')
#     parser.add_argument('--architecture', type=str, default='yolov7', help='model architecture')
#     parser.add_argument('--weights', type=str, required=True, help='path to pretrained weights')
#     parser.add_argument('--data', type=str, required=True, help='*.data path')
#     parser.add_argument('--bsz-train', type=int, default=16, help='batch size for training')
#     parser.add_argument('--bsz-val', type=int, default=16, help='batch size for evaluation')
#     parser.add_argument('--img', type=int, default=640, help='image size')
#     parser.add_argument('--conf', type=float, default=0.001, help='confidence threshold')
#     parser.add_argument('--iou', type=float, default=0.65, help='IOU threshold for NMS')
#     parser.add_argument('--cfg', type=str, default='yolov7/cfg/training/yolov7.yaml', help='model.yaml path')
#     parser.add_argument('--hyp', type=str, required=True, help='hyperparameters path')
#     parser.add_argument('--workers', type=int, default=4, help='number of workers')
#     parser.add_argument('--use-oort', action='store_true', help='Enable Oort client selection')
#     parser.add_argument('--oort-exploration', type=float, default=0.9, help='Oort exploration factor')
#     args = parser.parse_args()

#     # Initialize server
#     print("Initializing server...")
#     server = Server(args.server_opt, args.server_lr, args.tau, args.beta, use_oort = args.use_oort)
#     server.get_device_info()
    
#     # Initialize clients
#     print(f"Initializing {args.cclients} clients...")
#     clients = []
#     with open(args.data) as f:
#         data_dict = yaml.load(f, Loader=yaml.SafeLoader)
    
#     for i in range(1, args.nclients + 1):
#         client = Client(rank=i)
#         client.get_device_info()
        
#         # Count samples for each client
#         try:
#             img_path = os.path.join(data_dict['train'], f'client{i}', 'images')
#             client.nsamples = len(os.listdir(img_path))
#             print(f"Client {i}: {client.nsamples} training samples")
#         except Exception as e:
#             print(f"Warning: Could not count samples for client {i}: {e}")
#             client.nsamples = 1  # default
        
#         clients.append(client)
    
#     # Create saving folder
#     saving_path = 'experiments'
#     os.makedirs(saving_path, exist_ok=True)
#     os.makedirs(f'{saving_path}/weights/', exist_ok=True)
#     os.makedirs(f'{saving_path}/run/', exist_ok=True)
    
#     # Save configuration
#     with open(f'{saving_path}/config.txt', 'w') as f:
#         f.write(f'nrounds: {args.nrounds}\n')
#         f.write(f'epochs: {args.epochs}\n')
#         f.write(f'nclients: {args.nclients}\n')
#         f.write(f'server opt: {args.server_opt}\n')
#         f.write(f'server learning rate: {args.server_lr}\n')
#         if args.server_opt == 'fedavgm':
#             f.write(f'beta: {args.beta}\n')
#         if args.server_opt in ['fedadagrad', 'fedadam', 'fedyogi']:
#             f.write(f'tau: {args.tau}\n')
#         f.write(f'architecture: {args.architecture}\n')
#         f.write(f'weights: {args.weights}\n')
#         f.write(f'data: {args.data}\n')
#         f.write(f'batch size (train): {args.bsz_train}\n')
#         f.write(f'batch size (eval): {args.bsz_val}\n')
#         f.write(f'img: {args.img}\n')
#         f.write(f'cfg: {args.cfg}\n')
#         f.write(f'hyp: {args.hyp}\n')
    
#     try:
#         shutil.copy(args.cfg, saving_path)
#         shutil.copy(args.hyp, saving_path)
#         shutil.copy(args.data, saving_path)
#     except Exception as e:
#         print(f"Warning: Could not copy config files: {e}")
    
#     # Run federated learning
#     print("\nStarting federated learning...")
#     federated_loop(
#     server=server,
#     clients=clients,
#     nrounds=args.nrounds,
#     epochs=args.epochs,
#     saving_path=saving_path,
#     architecture=args.architecture,
#     pretrained_weights=args.weights,
#     data=args.data,
#     bsz_train=args.bsz_train,
#     bsz_val=args.bsz_val,
#     imgsz=args.img,
#     conf_thres=args.conf,
#     iou_thres=args.iou,
#     cfg=args.cfg,
#     hyp=args.hyp,
#     workers=args.workers,
#     selection_ratio=args.selection_ratio,
#     oort_start_round=args.oort_start_round
# )

    
#     # Gather analytics
#     print("\nGathering analytics...")
#     gather_analytics(saving_path, clients)
    
#     print("\nFederated learning completed!")


# main.py
import logging
import time
import argparse
import os
import shutil
import sys
sys.path.append('yolov7')

import pandas as pd
import yaml

from node import Client, Server

# Try to import predefined clients if user created them externally
try:
    # expected: predefined_clients.py contains "clients = [Client(...), ...]"
    from predefined_clients import clients as predefined_clients_list
except Exception:
    predefined_clients_list = None


def federated_loop(server: Server, clients: list, nrounds: int, epochs: int,
                   saving_path: str, architecture: str, pretrained_weights: str,
                   data: str, bsz_train: int, bsz_val: int, imgsz: int,
                   conf_thres: float, iou_thres: float, cfg: str, hyp: str,
                   workers: int, selection_ratio: float = 1.0, oort_start_round: int = 1) -> None:
    """
    Orchestrate the federated learning experiment in a sequential manner.

    selection_ratio: fraction of clients to choose (e.g. 0.3)
    oort_start_round: round index (0-based) to start Oort selection. If 0 then Oort from round 0.
    """

    print(len(clients))
    # Register clients to Oort if used
    if server.use_oort:
        for client in clients:
            server.oort_sampler.register_client(
                client.rank,
                client.nsamples,
                duration=1.0  # initial estimate
            )

    # Server initializes model
    print("Initializing model on server...")
    server.initialize_model(pretrained_weights)
    server.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)

    total_clients = len(clients)
    print(f"[Main] total clients = {total_clients}")

    for kround in range(nrounds):
        print(f"\n{'='*50}")
        print(f"Round {kround + 1}/{nrounds}")
        print(f"{'='*50}")

        # Round 0: share initial weights with clients
        if kround == 0:
            initial_weights = server.get_weights(metadata=True)
            for client in clients:
                client.set_weights(initial_weights, metadata=True)
                client.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)

        # Determine active clients (Oort or all)
        if server.use_oort and kround >= oort_start_round:
            feasible = [c.rank for c in clients]
            num_to_select = max(1, int(total_clients * selection_ratio))
            print(f"[Oort] round={kround} selecting num_to_select={num_to_select}")
            selected_ranks = server.oort_sampler.select_clients(
                num_clients=num_to_select,
                feasible_clients=feasible,
                round_num=kround
            )
            print(f"[Oort DEBUG] selected_ranks = {selected_ranks}")
            active_clients = [c for c in clients if c.rank in selected_ranks]
            print(f"[Oort] Selected {len(active_clients)}/{len(clients)} clients -> {[c.rank for c in active_clients]}")
        else:
            active_clients = clients
            if server.use_oort:
                print(f"[Oort] Warmup/start phase (round {kround}): using all clients")

        updates = []
        nsamples_list = []
        client_durations = []
        client_losses = []

        for client in active_clients:
            print(f"\n--- Training Client {client.rank} ---")
            train_start = time.time()

            # Call the client's train; adapt if your Client.train signature differs
            client.train(
                nrounds=nrounds,
                kround=kround,
                epochs=epochs,
                architecture=architecture,
                data=data,
                bsz_train=bsz_train,
                imgsz=imgsz,
                cfg=cfg,
                hyp=hyp,
                workers=workers,
                saving_path=saving_path
            )

            train_duration = time.time() - train_start
            client_durations.append(train_duration)
            update = client.get_update()
            updates.append(update)
            nsamples_list.append(client.nsamples)
            
            client_loss = None
            if isinstance(update, dict):
                client_loss = update.get('loss')
            # fallback if not present
            if client_loss is None:
            # Optionally try reading a file produced by client training, else fallback to small positive
                client_loss = 0.5
            client_losses.append(client_loss)
            print(f"  Loss: {client_loss:.4f}")
            print(f"  Duration: {train_duration:.2f}s")
            print(f"  Samples: {client.nsamples}")

            # Update Oort with real loss if possible
            if server.use_oort and kround >= oort_start_round:
                server.oort_sampler.update_client(
                    client.rank,
                    loss=client_loss,
                    duration=train_duration,
                    round_num=kround
                )
            

        # Server aggregation
        print(f"\n--- Server Aggregation ---")
        server.aggregate(updates, nsamples_list)
        server.reparameterize(architecture)

        # Server evaluation
        print(f"\n--- Server Evaluation ---")
        server.test(kround, saving_path, data, bsz_val, imgsz, conf_thres, iou_thres)

        # Broadcast new weights to all clients
        new_weights = server.get_weights(metadata=False)
        for client in clients:
            client.set_weights(new_weights, metadata=False)


def gather_analytics(saving_path: str, clients: list, server=None) -> None:
    """Gather local analytics from clients; if server (with Oort) provided, save Oort utilities too."""
    os.makedirs(f'{saving_path}/run/local-analytics/', exist_ok=True)

    for client in clients:
        rank = client.rank
        try:
            df_lr = pd.read_csv(f'{saving_path}/run/train-client{rank}/optim_params.csv')
            df_loss = pd.read_csv(f'{saving_path}/run/train-client{rank}/training_losses.csv')

            df_lr.to_csv(f'{saving_path}/run/local-analytics/optim_params_{rank}.csv', index=False)
            df_loss.to_csv(f'{saving_path}/run/local-analytics/training_losses_{rank}.csv', index=False)

            if os.path.exists(f'{saving_path}/run/train-client{rank}/opt.yaml'):
                with open(f'{saving_path}/run/train-client{rank}/opt.yaml') as f:
                    save_yaml = yaml.load(f, Loader=yaml.SafeLoader)
                with open(f'{saving_path}/run/local-analytics/opt_{rank}.yaml', 'w') as f:
                    yaml.dump(save_yaml, f)
        except Exception as e:
            print(f"Warning: Could not gather analytics for client {rank}: {e}")

    # Save Oort utilities if server provided
    if server is not None and getattr(server, 'use_oort', False) and hasattr(server, 'oort_sampler'):
        try:
            utilities = {}
            for client_id, info in server.oort_sampler.selector.totalArms.items():
                utilities[client_id] = {
                    'reward': info.get('reward', 0.0),
                    'duration': info.get('duration', 0.0),
                    'count': info.get('count', 0),
                    'last_selected_round': info.get('time_stamp', -1)
                }
            df_util = pd.DataFrame.from_dict(utilities, orient='index')
            df_util.to_csv(f'{saving_path}/run/local-analytics/oort_utilities.csv')
            print(f"[INFO] Oort utilities saved for {len(utilities)} clients.")
        except Exception as e:
            print(f"Warning: Could not gather Oort utilities: {e}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--nrounds', type=int, default=30, help='number of communication rounds')
    parser.add_argument('--epochs', type=int, default=5, help='number of epochs per round')
    # removed --nclients on purpose (clients comes from predefined or detected)
    parser.add_argument('--server-opt', type=str, default='fedavg', help='aggregation algorithm')
    parser.add_argument('--server-lr', type=float, default=1., help='server learning rate')
    parser.add_argument('--tau', type=float, default=1e-3, help='server adaptivity')
    parser.add_argument('--beta', type=float, default=0.1, help='server momentum')
    parser.add_argument('--architecture', type=str, default='yolov7', help='model architecture')
    parser.add_argument('--weights', type=str, required=True, help='path to pretrained weights')
    parser.add_argument('--data', type=str, required=True, help='*.data path (yaml)')
    parser.add_argument('--bsz-train', type=int, default=16, help='batch size for training')
    parser.add_argument('--bsz-val', type=int, default=16, help='batch size for evaluation')
    parser.add_argument('--img', type=int, default=640, help='image size')
    parser.add_argument('--conf', type=float, default=0.001, help='confidence threshold')
    parser.add_argument('--iou', type=float, default=0.65, help='IOU threshold for NMS')
    parser.add_argument('--cfg', type=str, default='yolov7/cfg/training/yolov7.yaml', help='model.yaml path')
    parser.add_argument('--hyp', type=str, required=True, help='hyperparameters path')
    parser.add_argument('--workers', type=int, default=4, help='number of workers')

    # Oort / selection args
    parser.add_argument('--use-oort', action='store_true', help='Enable Oort client selection')
    parser.add_argument('--selection-ratio', type=float, default=1.0, help='fraction of clients selected each round (if using Oort)')
    parser.add_argument('--oort-start-round', type=int, default=1, help='round index to start Oort client selection')

    args = parser.parse_args()

    # Initialize server
    print("Initializing server...")
    server = Server(args.server_opt, args.server_lr, args.tau, args.beta, use_oort=args.use_oort)
    server.get_device_info()

    # Initialize clients: try predefined list first, otherwise detect from data/train folders
    if predefined_clients_list is not None:
        clients = predefined_clients_list
        print(f"Loaded {len(clients)} predefined clients.")
    else:
        print("No predefined_clients.py found, detecting clients from dataset folder...")
        with open(args.data) as f:
            data_dict = yaml.load(f, Loader=yaml.SafeLoader)
        train_root = data_dict.get('train')
        if train_root is None:
            raise RuntimeError("data yaml must contain 'train' path (where client subfolders are).")
        client_dirs = sorted([d for d in os.listdir(train_root) if d.startswith("client")])
        clients = []
        for idx, dirname in enumerate(client_dirs, start=1):
            client = Client(rank=idx)
            client.get_device_info()
            img_path = os.path.join(train_root, dirname, "images")
            try:
                client.nsamples = len(os.listdir(img_path))
            except Exception:
                client.nsamples = 1
            clients.append(client)
        print(f"Detected {len(clients)} clients from {train_root}.")

    # Create saving folder
    saving_path = 'experiments'
    os.makedirs(saving_path, exist_ok=True)
    os.makedirs(f'{saving_path}/weights/', exist_ok=True)
    os.makedirs(f'{saving_path}/run/', exist_ok=True)

    # Save configuration
    with open(f'{saving_path}/config.txt', 'w') as f:
        f.write(f'nrounds: {args.nrounds}\n')
        f.write(f'epochs: {args.epochs}\n')
        f.write(f'server opt: {args.server_opt}\n')
        f.write(f'server learning rate: {args.server_lr}\n')
        if args.server_opt == 'fedavgm':
            f.write(f'beta: {args.beta}\n')
        if args.server_opt in ['fedadagrad', 'fedadam', 'fedyogi']:
            f.write(f'tau: {args.tau}\n')
        f.write(f'architecture: {args.architecture}\n')
        f.write(f'weights: {args.weights}\n')
        f.write(f'data: {args.data}\n')
        f.write(f'batch size (train): {args.bsz_train}\n')
        f.write(f'batch size (eval): {args.bsz_val}\n')
        f.write(f'img: {args.img}\n')
        f.write(f'cfg: {args.cfg}\n')
        f.write(f'hyp: {args.hyp}\n')

    try:
        shutil.copy(args.cfg, saving_path)
        shutil.copy(args.hyp, saving_path)
        shutil.copy(args.data, saving_path)
    except Exception as e:
        print(f"Warning: Could not copy config files: {e}")

    # Run federated learning
    print("\nStarting federated learning...")
    federated_loop(
        server=server,
        clients=clients,
        nrounds=args.nrounds,
        epochs=args.epochs,
        saving_path=saving_path,
        architecture=args.architecture,
        pretrained_weights=args.weights,
        data=args.data,
        bsz_train=args.bsz_train,
        bsz_val=args.bsz_val,
        imgsz=args.img,
        conf_thres=args.conf,
        iou_thres=args.iou,
        cfg=args.cfg,
        hyp=args.hyp,
        workers=args.workers,
        selection_ratio=args.selection_ratio,
        oort_start_round=args.oort_start_round
    )

    # Gather analytics (and save Oort utilities if used)
    print("\nGathering analytics...")
    gather_analytics(saving_path, clients, server=server)

    print("\nFederated learning completed!")
