

# import argparse
# import os
# import shutil
# import sys
# sys.path.append('yolov7')

# # from mpi4py import MPI
# from mpi4py import MPI
# import pandas as pd
# import yaml

# from node import Client, Node, Server


# def init_node(rank: int, server_opt: str, server_lr: float, tau: float, beta: float) -> Node:
#     """Initialize a node (client or server) based on its rank."""
#     available_optimizers = ['fedavg', 'fedavgm', 'fedadagrad', 'fedadam', 'fedyogi']
#     if server_opt not in available_optimizers:
#         raise ValueError(f'Server optimizer {server_opt} unavailable, must be in {available_optimizers}.')
#     return Server(server_opt, server_lr, tau, beta) if rank == 0 else Client(rank)


# def share_public_keys(node: Node) -> None:
#     """Clients receive the server's public key while the server receives each client's public key."""
#     key_rank_pairs = comm.gather((node.rank, node.public_key), root=0)
#     if node.rank == 0:
#         key_rank_pairs = {r: cpk for r, cpk in key_rank_pairs}
#         key_rank_pairs.pop(0)
#         node.clients_public_keys = key_rank_pairs
#     public_key = comm.bcast(node.public_key, root=0)
#     if node.rank != 0:
#         node.server_public_key = public_key


# def share_symmetric_key(node: Node) -> None:
#     """The symmetric key is generated by the server and shared among the clients using asymmetric encryption."""
#     if node.rank == 0:
#         node.generate_symmetric_key()
#         sk = [None] + node.get_symmetric_key()
#     else:
#         sk = None
#     sk = comm.scatter(sk, root=0)
#     if node.rank != 0:
#         node.symmetric_key = sk


# def initial_broadcast(node: Node, pretrained_weights: str, data: str, cfg: str, hyp: str, imgsz: int) -> None:
#     """The central server initializes the checkpoint from a pretrained weights file and shares it with the clients."""
#     if node.rank == 0:
#         node.initialize_model(pretrained_weights)
#         encrypted_data = [None] + node.get_weights(metadata=True)
#         node.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)
#     else:
#         encrypted_data = None
#     encrypted_data = comm.scatter(encrypted_data, root=0)
#     if node.rank != 0:
#         node.set_weights(encrypted_data, metadata=True)


# def federated_loop(node: Node, nrounds: int, epochs: int, saving_path: str, architecture: str, pretrained_weights: str,
#                    data: str, bsz_train: int, bsz_val: int, imgsz: int, conf_thres: float, iou_thres: float, cfg: str,
#                    hyp: str, workers: int) -> None:
#     """Orchestrate the federated learning experiment."""
#     for kround in range(nrounds):
#         # At the beginning of a round, generate and share a new symmetric key
#         share_symmetric_key(node)
#         # If it is the first round, the central server sends the initial checkpoint to the clients
#         if kround == 0:
#             initial_broadcast(node, pretrained_weights, data, cfg, hyp, imgsz)
#         # Client level computation (local training)
#         if node.rank != 0:
#             node.train(nrounds, kround, epochs, architecture, data, bsz_train, imgsz, cfg, hyp, workers, saving_path)
#             sd_encrypted = node.get_update()
#         else:
#             sd_encrypted = None
#         # Updates are gathered by the central server
#         sd_encrypted = comm.gather(sd_encrypted, root=0)
#         # Server level computation (server optimization, re-parameterization, and evaluation on the validation set)
#         if node.rank == 0:
#             for i, item in enumerate(sd_encrypted):
#                 print(f"[Server] Received update from rank {i}: {type(item)}")
#             sd_encrypted.pop(0)
#             node.aggregate(sd_encrypted)
#             node.reparameterize(architecture)
#             node.test(kround, saving_path, data, bsz_val, imgsz, conf_thres, iou_thres)
#             sd_encrypted = [None] + node.get_weights(metadata=False)
#         else:
#             sd_encrypted = None
#         # New weights are shared with the clients
#         sd_encrypted = comm.scatter(sd_encrypted, root=0)
#         if node.rank != 0:
#             node.set_weights(sd_encrypted, metadata=False)


# def gather_analytics(saving_path: str, node: Node) -> None:
#     """Gather local analytics from the client nodes' local storage back to the server's local storage."""
#     os.makedirs(f'{saving_path}/run/local-analytics/')
#     if node.rank != 0:
#         df_lr = pd.read_csv(f'{saving_path}/run/train-client{node.rank}/optim_params.csv')
#         df_loss = pd.read_csv(f'{saving_path}/run/train-client{node.rank}/training_losses.csv')
#         with open(f'{saving_path}/run/train-client{node.rank}/opt.yaml') as f:
#             save_yaml = yaml.load(f, Loader=yaml.SafeLoader)
#         local_analytics = (df_lr, df_loss, save_yaml)
#     else:
#         local_analytics = None, None, None
#     local_analytics = comm.gather(local_analytics, root=0)
#     if node.rank == 0:
#         for i, (df_lr, df_loss, save_yaml) in enumerate(local_analytics):
#             if i != 0:
#                 df_lr.to_csv(f'{saving_path}/run/local-analytics/optim_params_{i}.csv')
#                 df_loss.to_csv(f'{saving_path}/run/local-analytics/training_losses_{i}.csv')
#                 with open(f'{saving_path}/run/local-analytics/opt_{i}.yaml', 'w') as f:
#                     yaml.dump(save_yaml, f)

# def local_federated_loop(n_clients: int, nrounds: int, epochs: int, saving_path: str,
#                          architecture: str, pretrained_weights: str, data: str,
#                          bsz_train: int, bsz_val: int, imgsz: int, conf_thres: float,
#                          iou_thres: float, cfg: str, hyp: str, workers: int,
#                          server_opt: str, server_lr: float, tau: float, beta: float):

#     # 1ï¸âƒ£ Khá»Ÿi táº¡o server vÃ  cÃ¡c client
#     server = Server(server_opt, server_lr, tau, beta)
#     clients = [Client(rank=i+1) for i in range(n_clients)]

#     print(f"[Setup] Initialized {n_clients} clients and 1 server.")

#     # 2ï¸âƒ£ Server gá»­i model khá»Ÿi táº¡o
#     server.initialize_model(pretrained_weights)
#     weights = server.get_weights(metadata=True)

#     for c in clients:
#         c.set_weights(weights, metadata=True)
#         c.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)

#     # 3ï¸âƒ£ VÃ²ng láº·p federated learning
#     for kround in range(nrounds):
#         print(f"\n====== Round {kround+1}/{nrounds} ======")

#         updates = []
#         for i, client in enumerate(clients, 1):
#             print(f"\n[Client {i}] Local training...")
#             client.train(nrounds, kround, epochs, architecture, data, bsz_train, imgsz, cfg, hyp, workers, saving_path)
#             updates.append(client.get_update())

#         print("\n[Server] Aggregating updates...")
#         server.aggregate(updates)
#         server.reparameterize(architecture)
#         server.test(kround, saving_path, data, bsz_val, imgsz, conf_thres, iou_thres)

#         # Broadcast new weights
#         new_weights = server.get_weights(metadata=False)
#         for c in clients:
#             c.set_weights(new_weights, metadata=False)

#     print("\nâœ… Federated training finished successfully.")


# def federated_secure_loop(num_clients, nrounds, epochs, saving_path,
#                           architecture, pretrained_weights, data,
#                           bsz_train, bsz_val, imgsz, conf_thres,
#                           iou_thres, cfg, hyp, workers):
#     """
#     MÃ´ phá»ng Federated Learning cÃ³ mÃ£ hÃ³a nhÆ°ng cháº¡y tuáº§n tá»± trÃªn Kaggle.
#     Giá»¯ nguyÃªn cÆ¡ cháº¿ mÃ£ hÃ³a cá»§a FedPylot (public/private/symmetric).
#     """

#     # ===== 1. Táº¡o server vÃ  client =====
#     print("ðŸš€ Initializing Server and Clients...")
#     server = Server(server_opt='fedavg', serverlr=1.0, tau=1e-3, beta=0.1)
#     clients = [Client(rank=i + 1) for i in range(num_clients)]

#     # ===== 2. Trao Ä‘á»•i public keys =====
#     print("ðŸ” Exchanging public keys...")
#     for client in clients:
#         client.server_public_key = server.public_key
#     server.clients_public_keys = {client.rank: client.public_key for client in clients}

#     # ===== 3. Server khá»Ÿi táº¡o model vÃ  symmetric key =====
#     print("ðŸ§  Initializing model and symmetric keys...")
#     server.initialize_model(pretrained_weights)
#     server.generate_symmetric_key()

#     # symmetric_keys: list[encrypted_symmetric_key_for_each_client]
#     symmetric_keys = server.get_symmetric_key()

#     # ===== 4. Má»—i client nháº­n symmetric key vÃ  model khá»Ÿi táº¡o =====
#     print("ðŸ“¦ Distributing initial model to clients...")
#     encrypted_models = server.get_weights(metadata=True)
#     for i, client in enumerate(clients):
#         client.symmetric_key = symmetric_keys[i]   # key riÃªng cho client i
#         client.set_weights(encrypted_models[i], metadata=True)
#         client.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)

#     # ===== 5. VÃ²ng láº·p Federated Learning =====
#     for rnd in range(nrounds):
#         print(f"\nðŸŒ ROUND {rnd + 1}/{nrounds}")
#         encrypted_updates = []

#         # --- Clients: local training ---
#         for client in clients:
#             print(f"ðŸ‹ï¸ Client {client.rank} training locally...")
#             client.train(nrounds, rnd, epochs, architecture, data,
#                          bsz_train, imgsz, cfg, hyp, workers, saving_path)
#             update = client.get_update()  # encrypted gradient/update
#             encrypted_updates.append(update)

#         # --- Server: aggregate + reparameterize ---
#         print("ðŸ–¥ï¸ Server aggregating encrypted updates...")
#         server.aggregate(encrypted_updates)
#         server.reparameterize(architecture)

#         # --- Server: evaluate on validation set ---
#         server.test(rnd, saving_path, data, bsz_val, imgsz, conf_thres, iou_thres)

#         # --- Server gá»­i model má»›i cho cÃ¡c client ---
#         print("ðŸ“¤ Broadcasting new global weights to clients...")
#         new_encrypted_weights = server.get_weights(metadata=False)
#         for client in clients:
#             client.set_weights(new_encrypted_weights, metadata=False)

#     print("\nâœ… Secure Federated Learning simulation completed successfully!")



# # if __name__ == "__main__":
# #     parser = argparse.ArgumentParser()
# #     parser.add_argument('--nrounds', type=int, default=3)
# #     parser.add_argument('--epochs', type=int, default=1)
# #     parser.add_argument('--nclients', type=int, default=2, help='number of simulated clients')
# #     parser.add_argument('--server-opt', type=str, default='fedavg')
# #     parser.add_argument('--server-lr', type=float, default=1.)
# #     parser.add_argument('--tau', type=float, default=1e-3)
# #     parser.add_argument('--beta', type=float, default=0.1)
# #     parser.add_argument('--architecture', type=str, default='yolov7')
# #     parser.add_argument('--weights', type=str, help='path to pretrained weights')
# #     parser.add_argument('--data', type=str, help='*.data path')
# #     parser.add_argument('--bsz-train', type=int, default=16)
# #     parser.add_argument('--bsz-val', type=int, default=16)
# #     parser.add_argument('--img', type=int, default=640)
# #     parser.add_argument('--conf', type=float, default=0.001)
# #     parser.add_argument('--iou', type=float, default=0.65)
# #     parser.add_argument('--cfg', type=str, default='yolov7/cfg/training/yolov7.yaml')
# #     parser.add_argument('--hyp', type=str)
# #     parser.add_argument('--workers', type=int, default=4)
# #     args = parser.parse_args()

# #     saving_path = 'experiments'
# #     os.makedirs(f"{saving_path}/weights", exist_ok=True)
# #     os.makedirs(f"{saving_path}/run", exist_ok=True)

# #     federated_secure_loop(
# #         num_clients=args.nclients,
# #         nrounds=args.nrounds,
# #         epochs=args.epochs,
# #         saving_path=saving_path,
# #         architecture=args.architecture,
# #         pretrained_weights=args.weights,
# #         data=args.data,
# #         bsz_train=args.bsz_train,
# #         bsz_val=args.bsz_val,
# #         imgsz=args.img,
# #         conf_thres=args.conf,
# #         iou_thres=args.iou,
# #         cfg=args.cfg,
# #         hyp=args.hyp,
# #         workers=args.workers,
# #     )


# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--nrounds', type=int, default=30, help='number of communication rounds')
#     parser.add_argument('--epochs', type=int, default=5, help='number of epochs executed per communication round')
#     parser.add_argument('--server-opt', type=str, default='fedavg', help='aggregation algorithm/server-side optimizer')
#     parser.add_argument('--server-lr', type=float, default=1., help='server learning rate')
#     parser.add_argument('--tau', type=float, default=1e-3, help='server adaptivity for FedAdagrad, FedAdam and FedYogi')
#     parser.add_argument('--beta', type=float, default=0.1, help='server momentum with FedAvgM')
#     parser.add_argument('--architecture', type=str, default='yolov7', help='model architecture')
#     parser.add_argument('--weights', type=str, help='path to pretrained weights')
#     parser.add_argument('--data', type=str, help='*.data path')
#     parser.add_argument('--bsz-train', type=int, default=32, help='batch size used for training')
#     parser.add_argument('--bsz-val', type=int, default=32, help='batch size used for evaluation')
#     parser.add_argument('--img', type=int, default=640, help='inference size (pixels)')
#     parser.add_argument('--conf', type=float, default=0.001, help='object confidence threshold')
#     parser.add_argument('--iou', type=float, default=0.65, help='IOU threshold for NMS')
#     parser.add_argument('--cfg', type=str, default='yolov7/cfg/training/yolov7.yaml', help='model.yaml path')
#     parser.add_argument('--hyp', type=str, help='hyperparameters path, also decides client-side optimizer')
#     parser.add_argument('--workers', type=int, default=8, help='number of workers to use during training')
#     args = parser.parse_args()

#     # Initialize MPI
#     comm = MPI.COMM_WORLD
#     rank = comm.Get_rank()
#     node = init_node(rank, args.server_opt, args.server_lr, args.tau, args.beta)
#     node.get_device_info()

#     # Save the number of training examples held by the clients to perform weighted average aggregation of the updates
#     with open(args.data) as f:
#         if node.rank != 0:
#             img_path = os.path.join(yaml.load(f, Loader=yaml.SafeLoader)['train'], f'client{node.rank}', 'images')
#             node.nsamples = len(os.listdir(img_path))

#     # The clients exchange their public keys with the central server and vice-versa
#     share_public_keys(node)

#     # Create saving folder
#     saving_path = 'experiments'
#     os.makedirs(saving_path)
#     os.makedirs(saving_path + '/weights/')
#     os.makedirs(saving_path + '/run/')

#     # Save config, cfg, hyp and data files
#     if node.rank == 0:
#         with open(saving_path + '/config.txt', 'w') as f:
#             f.write(f'nrounds: {args.nrounds}\n')
#             f.write(f'epochs: {args.epochs}\n')
#             f.write(f'server opt: {args.server_opt}\n')
#             f.write(f'server learning rate: {args.server_lr}\n')
#             if args.server_opt == 'fedavgm':
#                 f.write(f'fedavgm - beta: {args.beta}\n')
#             if args.server_opt == 'fedadagrad':
#                 f.write(f'fedadagrad - tau: {args.tau}\n')
#             if args.server_opt in ['fedadam', 'fedyogi']:
#                 f.write(f'{args.server_opt} - tau: {args.tau}\n')
#                 f.write(f'{args.server_opt} - beta1: {0.9}\n')
#                 f.write(f'{args.server_opt} - beta2: {0.99}\n')
#             f.write(f'architecture: {args.architecture}\n')
#             f.write(f'weights: {args.weights}\n')
#             f.write(f'data: {args.data}\n')
#             f.write(f'batch size (train): {args.bsz_train}\n')
#             f.write(f'batch size (eval): {args.bsz_val}\n')
#             f.write(f'img: {args.img}\n')
#             f.write(f'conf: {args.conf}\n')
#             f.write(f'iou: {args.iou}\n')
#             f.write(f'cfg: {args.cfg}\n')
#             f.write(f'hyp: {args.hyp}\n')
#             f.write(f'workers: {args.workers}\n')
#         shutil.copy(args.cfg, saving_path)
#         shutil.copy(args.hyp, saving_path)
#         shutil.copy(args.data, saving_path)

#     # Launch federated learning experiment
#     federated_loop(
#         node=node,
#         nrounds=args.nrounds,
#         epochs=args.epochs,
#         saving_path=saving_path,
#         architecture=args.architecture,
#         pretrained_weights=args.weights,
#         data=args.data,
#         bsz_train=args.bsz_train,
#         bsz_val=args.bsz_val,
#         imgsz=args.img,
#         conf_thres=args.conf,
#         iou_thres=args.iou,
#         cfg=args.cfg,
#         hyp=args.hyp,
#         workers=args.workers
#     )

#     # Gather clients' local analytics back to the orchestrating node in order to back up the files
#     gather_analytics(saving_path, node)




# import logging
# import time
# import argparse
# import os
# import shutil
# import sys
# sys.path.append('yolov7')

# import pandas as pd
# import yaml

# from node import Client, Server


# def federated_loop(server: Server, clients: list, nrounds: int, epochs: int, 
#                    saving_path: str, architecture: str, pretrained_weights: str, 
#                    data: str, bsz_train: int, bsz_val: int, imgsz: int, 
#                    conf_thres: float, iou_thres: float, cfg: str, hyp: str, 
#                    workers: int) -> None:
    
#     # === ÄÄ‚NG KÃ CLIENTS VÃ€O OORT ===
#     if server.use_oort:
#         for client in clients:
#             server.oort_sampler.register_client(
#                 client.rank,
#                 client.nsamples,
#                 duration=1.0  # Initial estimate
#             )
#     # === END ===
    
#     # Server initializes model
#     print("Initializing model on server...")
#     server.initialize_model(pretrained_weights)
#     server.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)
    
#     for kround in range(nrounds):
#         print(f"\n{'='*50}")
#         print(f"Round {kround + 1}/{nrounds}")
#         print(f"{'='*50}")
        
#         if kround == 0:
#             initial_weights = server.get_weights(metadata=True)
#             for client in clients:
#                 client.set_weights(initial_weights, metadata=True)
#                 client.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)
        
#         # === CHá»ŒN CLIENTS Báº°NG OORT ===
#         if server.use_oort and kround > 0:  # Skip round 0
#             feasible = [c.rank for c in clients]
#             selected_ranks = server.oort_sampler.select_clients(
#                 num_clients=len(clients),
#                 feasible_clients=feasible,
#                 round_num=kround
#             )
#             active_clients = [c for c in clients if c.rank in selected_ranks]
#             print(f"[Oort] Selected {len(active_clients)}/{len(clients)} clients")
#         else:
#             active_clients = clients
#         # === END ===
        
#         updates = []
#         nsamples_list = []
        
#         import time
#         for client in active_clients:
#             print(f"\n--- Training Client {client.rank} ---")
#             train_start = time.time()
            
#             client.train(...)
            
#             train_duration = time.time() - train_start
#             update = client.get_update()
#             updates.append(update)
#             nsamples_list.append(client.nsamples)
            
#             # === Cáº¬P NHáº¬T OORT STATS ===
#             if server.use_oort and kround > 0:
#                 # Assume loss is stored somewhere during training
#                 client_loss = 0.5  # Placeholder - get from actual training
#                 server.oort_sampler.update_client(
#                     client.rank,
#                     loss=client_loss,
#                     duration=train_duration,
#                     round_num=kround
#                 )
#             # === END ===
        
#         # Server aggregation
#         print(f"\n--- Server Aggregation ---")
#         server.aggregate(updates, nsamples_list)
#         server.reparameterize(architecture)
        
#         # Server evaluation
#         print(f"\n--- Server Evaluation ---")
#         server.test(kround, saving_path, data, bsz_val, imgsz, conf_thres, iou_thres)
        
#         # Broadcast new weights
#         new_weights = server.get_weights(metadata=False)
#         for client in clients:
#             client.set_weights(new_weights, metadata=False)


# def gather_analytics(saving_path: str, clients: list) -> None:
#     """Gather local analytics from clients."""
#     os.makedirs(f'{saving_path}/run/local-analytics/', exist_ok=True)
    
#     for client in clients:
#         rank = client.rank
#         try:
#             df_lr = pd.read_csv(f'{saving_path}/run/train-client{rank}/optim_params.csv')
#             df_loss = pd.read_csv(f'{saving_path}/run/train-client{rank}/training_losses.csv')
            
#             df_lr.to_csv(f'{saving_path}/run/local-analytics/optim_params_{rank}.csv', index=False)
#             df_loss.to_csv(f'{saving_path}/run/local-analytics/training_losses_{rank}.csv', index=False)
            
#             if os.path.exists(f'{saving_path}/run/train-client{rank}/opt.yaml'):
#                 with open(f'{saving_path}/run/train-client{rank}/opt.yaml') as f:
#                     save_yaml = yaml.load(f, Loader=yaml.SafeLoader)
#                 with open(f'{saving_path}/run/local-analytics/opt_{rank}.yaml', 'w') as f:
#                     yaml.dump(save_yaml, f)
#         except Exception as e:
#             print(f"Warning: Could not gather analytics for client {rank}: {e}")

# # def gather_analytics(saving_path: str, clients: list, server=None) -> None:
# #     """Gather local analytics from clients and optionally Oort utilities."""
# #     os.makedirs(f'{saving_path}/run/local-analytics/', exist_ok=True)
    
# #     for client in clients:
# #         rank = client.rank
# #         try:
# #             df_lr = pd.read_csv(f'{saving_path}/run/train-client{rank}/optim_params.csv')
# #             df_loss = pd.read_csv(f'{saving_path}/run/train-client{rank}/training_losses.csv')
            
# #             df_lr.to_csv(f'{saving_path}/run/local-analytics/optim_params_{rank}.csv', index=False)
# #             df_loss.to_csv(f'{saving_path}/run/local-analytics/training_losses_{rank}.csv', index=False)
            
# #             if os.path.exists(f'{saving_path}/run/train-client{rank}/opt.yaml'):
# #                 with open(f'{saving_path}/run/train-client{rank}/opt.yaml') as f:
# #                     save_yaml = yaml.load(f, Loader=yaml.SafeLoader)
# #                 with open(f'{saving_path}/run/local-analytics/opt_{rank}.yaml', 'w') as f:
# #                     yaml.dump(save_yaml, f)
# #         except Exception as e:
# #             print(f"Warning: Could not gather analytics for client {rank}: {e}")
    
# #     # LÆ°u utility náº¿u server vÃ  Oort cÃ³
# #     if server is not None and server.use_oort and hasattr(server, 'oort_sampler'):
# #         try:
# #             utilities = {}
# #             for client_id, info in server.oort_sampler.selector.totalArms.items():
# #                 utilities[client_id] = {
# #                     'reward': info['reward'],
# #                     'duration': info['duration'],
# #                     'count': info['count'],
# #                     'last_selected_round': info['time_stamp']
# #                 }
# #             df_util = pd.DataFrame.from_dict(utilities, orient='index')
# #             df_util.to_csv(f'{saving_path}/run/local-analytics/oort_utilities.csv')
# #             print(f"[INFO] Oort utilities saved for {len(utilities)} clients.")
# #         except Exception as e:
# #             print(f"Warning: Could not gather Oort utilities: {e}")



# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--nrounds', type=int, default=30, help='number of communication rounds')
#     parser.add_argument('--epochs', type=int, default=5, help='number of epochs per round')
#     parser.add_argument('--nclients', type=int, default=3, help='number of clients')
#     parser.add_argument('--server-opt', type=str, default='fedavg', help='aggregation algorithm')
#     parser.add_argument('--server-lr', type=float, default=1., help='server learning rate')
#     parser.add_argument('--tau', type=float, default=1e-3, help='server adaptivity')
#     parser.add_argument('--beta', type=float, default=0.1, help='server momentum')
#     parser.add_argument('--architecture', type=str, default='yolov7', help='model architecture')
#     parser.add_argument('--weights', type=str, required=True, help='path to pretrained weights')
#     parser.add_argument('--data', type=str, required=True, help='*.data path')
#     parser.add_argument('--bsz-train', type=int, default=16, help='batch size for training')
#     parser.add_argument('--bsz-val', type=int, default=16, help='batch size for evaluation')
#     parser.add_argument('--img', type=int, default=640, help='image size')
#     parser.add_argument('--conf', type=float, default=0.001, help='confidence threshold')
#     parser.add_argument('--iou', type=float, default=0.65, help='IOU threshold for NMS')
#     parser.add_argument('--cfg', type=str, default='yolov7/cfg/training/yolov7.yaml', help='model.yaml path')
#     parser.add_argument('--hyp', type=str, required=True, help='hyperparameters path')
#     parser.add_argument('--workers', type=int, default=4, help='number of workers')
#     parser.add_argument('--use-oort', action='store_true', help='Enable Oort client selection')
#     parser.add_argument('--oort-exploration', type=float, default=0.9, help='Oort exploration factor')
#     args = parser.parse_args()

#     # Initialize server
#     print("Initializing server...")
#     server = Server(args.server_opt, args.server_lr, args.tau, args.beta, use_oort = args.use_oort)
#     server.get_device_info()
    
#     # Initialize clients
#     print(f"Initializing {args.cclients} clients...")
#     clients = []
#     with open(args.data) as f:
#         data_dict = yaml.load(f, Loader=yaml.SafeLoader)
    
#     for i in range(1, args.nclients + 1):
#         client = Client(rank=i)
#         client.get_device_info()
        
#         # Count samples for each client
#         try:
#             img_path = os.path.join(data_dict['train'], f'client{i}', 'images')
#             client.nsamples = len(os.listdir(img_path))
#             print(f"Client {i}: {client.nsamples} training samples")
#         except Exception as e:
#             print(f"Warning: Could not count samples for client {i}: {e}")
#             client.nsamples = 1  # default
        
#         clients.append(client)
    
#     # Create saving folder
#     saving_path = 'experiments'
#     os.makedirs(saving_path, exist_ok=True)
#     os.makedirs(f'{saving_path}/weights/', exist_ok=True)
#     os.makedirs(f'{saving_path}/run/', exist_ok=True)
    
#     # Save configuration
#     with open(f'{saving_path}/config.txt', 'w') as f:
#         f.write(f'nrounds: {args.nrounds}\n')
#         f.write(f'epochs: {args.epochs}\n')
#         f.write(f'nclients: {args.nclients}\n')
#         f.write(f'server opt: {args.server_opt}\n')
#         f.write(f'server learning rate: {args.server_lr}\n')
#         if args.server_opt == 'fedavgm':
#             f.write(f'beta: {args.beta}\n')
#         if args.server_opt in ['fedadagrad', 'fedadam', 'fedyogi']:
#             f.write(f'tau: {args.tau}\n')
#         f.write(f'architecture: {args.architecture}\n')
#         f.write(f'weights: {args.weights}\n')
#         f.write(f'data: {args.data}\n')
#         f.write(f'batch size (train): {args.bsz_train}\n')
#         f.write(f'batch size (eval): {args.bsz_val}\n')
#         f.write(f'img: {args.img}\n')
#         f.write(f'cfg: {args.cfg}\n')
#         f.write(f'hyp: {args.hyp}\n')
    
#     try:
#         shutil.copy(args.cfg, saving_path)
#         shutil.copy(args.hyp, saving_path)
#         shutil.copy(args.data, saving_path)
#     except Exception as e:
#         print(f"Warning: Could not copy config files: {e}")
    
#     # Run federated learning
#     print("\nStarting federated learning...")
#     federated_loop(
#     server=server,
#     clients=clients,
#     nrounds=args.nrounds,
#     epochs=args.epochs,
#     saving_path=saving_path,
#     architecture=args.architecture,
#     pretrained_weights=args.weights,
#     data=args.data,
#     bsz_train=args.bsz_train,
#     bsz_val=args.bsz_val,
#     imgsz=args.img,
#     conf_thres=args.conf,
#     iou_thres=args.iou,
#     cfg=args.cfg,
#     hyp=args.hyp,
#     workers=args.workers,
#     selection_ratio=args.selection_ratio,
#     oort_start_round=args.oort_start_round
# )

    
#     # Gather analytics
#     print("\nGathering analytics...")
#     gather_analytics(saving_path, clients)
    
#     print("\nFederated learning completed!")


import math
import logging
import time
import argparse
import os
import shutil
import sys
import random
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "yolov7"))

import numpy as np
import pandas as pd
from scipy.stats import linregress
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import yaml
from sklearn.mixture import GaussianMixture


from node import Client, Server

# Try to import predefined clients if user created them externally
try:
    # expected: predefined_clients.py contains "clients = [Client(...), ...]"
    from predefined_clients import clients as predefined_clients_list
except Exception:
    predefined_clients_list = None


START_EPOCH_FOR_MEAN = 10 
LATE_RATIO           = 0.3  
ROUND_SIZE           = 5    
 
CLUSTER_FEATURES = [
    "LATE_MEAN_BOX_LOSS",
   # "BOX_SLOPE",
    "DELTA_STD",
   # "AUC_BOX_LOSS",
   # "LATE_BOX_SLOPE",
   # "FINAL_LOSS",
    "CONVERGENCE_RATIO",
   # "SMOOTHNESS",
    "LOSS_STD",
    "LOSS_RANGE",
   # "EARLY_SLOPE",
   # "SIGN_CHANGE_COUNT",
   # "PLATEAU_COUNT",
    "AVG_IMPROVEMENT",
   # "MAX_LOSS",
    "MIN_LOSS",
    "OSCILLATION",
]
 
def load_box_loss(saving_path: str, client_rank: int) -> np.ndarray | None:

    csv_path = os.path.join(
        saving_path, "run", f"train-client{client_rank}", "training_losses.csv"
    )
 
    if not os.path.exists(csv_path):
        print(f"  [WARN] Cannot find file: {csv_path}")
        return None
 
    df = pd.read_csv(csv_path)
 
    if "train/box_loss" in df.columns:
        col = "train/box_loss"
    elif "box_loss" in df.columns:
        col = "box_loss"
    else:
        print(f"  [WARN] Client {client_rank}: don not have box_loss column. "
              f"Only have: {df.columns.tolist()}")
        return None
 
    losses = pd.to_numeric(df[col], errors="coerce").dropna().values.astype(np.float64)
 
    if len(losses) < 5:
        print(f"  [WARN] Client {client_rank}: Have little epochs ({len(losses)}), Next.")
        return None
 
    return losses
 
 
def extract_box_features(losses: np.ndarray) -> dict | None:

    n = len(losses)
    if n < 5:
        return None
 
    epochs = np.arange(n)
    EPS    = 1e-4
    deltas = np.diff(losses)
 
    # 1. Late mean box loss
    start_idx          = min(START_EPOCH_FOR_MEAN, n - 1)
    late_mean_box_loss = np.mean(losses[start_idx:])
 
    # 2. Box slope 
    slope, *_ = linregress(epochs, losses)
 
    # 3. Delta std 
    delta_std = np.std(deltas)
 
    # 4. AUC box loss 
    auc_box_loss = (
        np.trapezoid(losses, epochs)
        if hasattr(np, "trapezoid")
        else np.trapz(losses, epochs)
    )
 
    # 5. Late box slope
    late_start = int(n * (1 - LATE_RATIO))
    late_slope, *_ = linregress(epochs[late_start:], losses[late_start:])
 
    # 6. Final loss 
    final_loss = losses[-1]
 
    # 7. Convergence ratio 
    convergence_ratio = (losses[-1] / losses[0]) if losses[0] != 0 else 0.0
 
    # 8. Smoothness 
    smoothness = np.mean(np.abs(deltas))
 
    # 9. Loss std 
    loss_std = np.std(losses)
 
    # 10. Loss range
    max_loss   = float(np.max(losses))
    min_loss   = float(np.min(losses))
    loss_range = max_loss - min_loss
 
    # 11. Early slope 
    early_end   = max(3, int(n * 0.3))
    early_slope, *_ = linregress(epochs[:early_end], losses[:early_end])
 
    # 12. Sign change count 
    sign_change_count = 0
    if len(deltas) > 1:
        prev = np.sign(deltas[0])
        for d in deltas[1:]:
            cur = np.sign(d)
            if cur != prev:
                sign_change_count += 1
            prev = cur
 
    # 13. Plateau count
    plateau_count = int(np.sum(np.abs(deltas) < EPS))
 
    # 14. Avg improvement
    n_rounds = n // ROUND_SIZE
    if n_rounds >= 2:
        round_means     = [losses[i*ROUND_SIZE:(i+1)*ROUND_SIZE].mean() for i in range(n_rounds)]
        avg_improvement = float(np.diff(round_means).mean())
    else:
        avg_improvement = 0.0
 
    # 15 & 16. Max / Min loss 
 
    # 17. Oscillation
    second_diff = np.diff(deltas)
    oscillation = float(np.mean(np.abs(second_diff)))
 
    return {
        "LATE_MEAN_BOX_LOSS": late_mean_box_loss,
        "BOX_SLOPE":          float(slope),
        "DELTA_STD":          float(delta_std),
        "AUC_BOX_LOSS":       float(auc_box_loss),
        "LATE_BOX_SLOPE":     float(late_slope),
        "FINAL_LOSS":         float(final_loss),
        "CONVERGENCE_RATIO":  float(convergence_ratio),
        "SMOOTHNESS":         float(smoothness),
        "LOSS_STD":           float(loss_std),
        "LOSS_RANGE":         float(loss_range),
        "EARLY_SLOPE":        float(early_slope),
        "SIGN_CHANGE_COUNT":  sign_change_count,
        "PLATEAU_COUNT":      plateau_count,
        "AVG_IMPROVEMENT":    avg_improvement,
        "MAX_LOSS":           max_loss,
        "MIN_LOSS":           min_loss,
        "OSCILLATION":        oscillation,
    }
 
 
def detect_noisy_clients(
    clients: list,
    saving_path: str,
    output_dir: str,
) -> tuple[list[int], list[int]]:
    """

    """
    os.makedirs(output_dir, exist_ok=True)
 
    print(f"\n{'='*60}")
    print("  [Noise Detection] Start to analyze loss curve of each client")
    print(f"{'='*60}")
 
    rows = []
    for client in clients:
        rank = client.rank
        print(f"\n  Client {rank}:")
 
        losses = load_box_loss(saving_path, rank)
        if losses is None:
            print(f"    Next (Do not have valid data).")
            continue
 
        print(f"    Epoch: {len(losses)} | "
              f"First Loss: {losses[0]:.5f} | Last Loss: {losses[-1]:.5f}")
 
        feats = extract_box_features(losses)
        if feats is None:
            print(f"    Next (Do not have enough dataset to calculate feature).")
            continue
 
        row = {"CLIENT": f"Client {rank}", "RANK": rank}
        row.update(feats)
        rows.append(row)
 
    # -- Do not have enough clients to cluster
    if len(rows) < 2:
        print("\n[WARN] Need at least 2 clients to cluster. "
              "Assume all clients are clean and continue.")
        all_ranks = [c.rank for c in clients]
        return [], all_ranks
 
    df = pd.DataFrame(rows)
 
    # -- Save features CSV -----------------------------------------------------
    feat_cols   = ["CLIENT"] + CLUSTER_FEATURES
    feat_path   = os.path.join(output_dir, "client_features_output.csv")
    df[feat_cols].to_csv(feat_path, index=False)
    print(f"\n  [OK] Features are saved ? {feat_path}")
 
    # -- KMeans clustering ----------------------------------------------------
    available_feats = [f for f in CLUSTER_FEATURES if f in df.columns]
    X        = df[available_feats].values
    X_scaled = StandardScaler().fit_transform(X)
 
    kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
    df["CLUSTER"] = kmeans.fit_predict(X_scaled)
 
    # Cluster have higher LATE_MEAN_BOX = NOISY 
    mean_loss = df.groupby("CLUSTER")["LATE_MEAN_BOX_LOSS"].mean()
    noisy_cluster = int(mean_loss.idxmax())
    clean_cluster = 1 - noisy_cluster
 
    df["LABEL"] = df["CLUSTER"].map({noisy_cluster: "NOISY", clean_cluster: "CLEAN"})
 
    # -- Save results CSV --------------------------------------------
    result_path = os.path.join(output_dir, "client_noise_detection.csv")
    df.to_csv(result_path, index=False)
    print(f"  [OK] save cluster ? {result_path}")
 
    # -- Print results -----------------------------------------------------------
    print(f"\n{'='*60}")
    print("  [Noise Detection] Result KMeans Clustering")
    print(f"{'='*60}")
    print(f"  Noisy cluster mean loss : {mean_loss[noisy_cluster]:.6f}")
    print(f"  Clean cluster mean loss : {mean_loss[clean_cluster]:.6f}")
    print()
 
    noisy_ranks, clean_ranks = [], []
    for _, row in df.iterrows():
        tag = "NOISY" if row["LABEL"] == "NOISY" else "CLEAN"
        print(f"  Client {row['RANK']:>2d}  "
              f"late_mean={row['LATE_MEAN_BOX_LOSS']:.5f}  "
              f"slope={row['BOX_SLOPE']:.6f}  "
              f"[{tag}]")
        if row["LABEL"] == "NOISY":
            noisy_ranks.append(int(row["RANK"]))
        else:
            clean_ranks.append(int(row["RANK"]))
 
    print(f"\n  Noisy clients ({len(noisy_ranks)}): {noisy_ranks}")
    print(f"  Clean clients ({len(clean_ranks)}): {clean_ranks}")
    print(f"{'='*60}\n")
 
    return noisy_ranks, clean_ranks


def filter_noisy_samples_gmm(noisy_ranks: list, saving_path: str, output_dir: str) -> dict:  
    """  
    Với mỗi noisy client, đọc per_sample_box_loss.csv, tính mean loss per image  
    qua tất cả các round/epoch, rồi dùng GMM 2 components để phân loại clean/noisy samples.  
      
    Returns:  
        dict mapping rank -> {'clean': [paths], 'noisy': [paths]}  
    """  
    os.makedirs(output_dir, exist_ok=True)  
    results = {}  
  
    for rank in noisy_ranks:  
        csv_path = f'{saving_path}/run/train-client{rank}/per_sample_box_loss.csv'  
        if not os.path.exists(csv_path):  
            print(f"  [WARN] Client {rank}: per_sample_box_loss.csv not found, skip.")  
            continue  
  
        df = pd.read_csv(csv_path)  
        if df.empty:  
            print(f"  [WARN] Client {rank}: per_sample_box_loss.csv is empty, skip.")  
            continue  
  
        # Compute mean box loss per image of epoch/batch  
        mean_loss = df.groupby('image_path')['box_loss'].mean().reset_index()  
        mean_loss.columns = ['image_path', 'mean_box_loss']  
  
        X = mean_loss['mean_box_loss'].values.reshape(-1, 1)  
  
        if len(X) < 2:  
            print(f"  [WARN] Client {rank}: not enough samples for GMM, skip.")  
            continue  
  
        # Fit GMM 2 components  
        gmm = GaussianMixture(n_components=2, random_state=42, max_iter=200)  
        gmm.fit(X)  
        labels = gmm.predict(X)  
  
        # Component has higher mean = noisy  
        comp_means = gmm.means_.flatten()  
        noisy_comp = int(comp_means.argmax())  
        clean_comp = 1 - noisy_comp  
  
        mean_loss['gmm_label'] = labels  
        mean_loss['sample_type'] = mean_loss['gmm_label'].map(  
            {noisy_comp: 'NOISY', clean_comp: 'CLEAN'}  
        )  
  
        # Save results to CSV file
        out_path = os.path.join(output_dir, f'sample_gmm_client{rank}.csv')  
        mean_loss.to_csv(out_path, index=False)  
  
        clean_paths = mean_loss[mean_loss['sample_type'] == 'CLEAN']['image_path'].tolist()  
        noisy_paths = mean_loss[mean_loss['sample_type'] == 'NOISY']['image_path'].tolist()  
        results[rank] = {'clean': clean_paths, 'noisy': noisy_paths}  
  
        print(f"  [OK] Client {rank}: {len(clean_paths)} clean, {len(noisy_paths)} noisy samples → {out_path}")  
        print(f"       GMM means: clean={comp_means[clean_comp]:.5f}, noisy={comp_means[noisy_comp]:.5f}")  
  
    return results
 
 

def federated_loop(server: Server, clients: list, nrounds: int, epochs: int,
                   saving_path: str, architecture: str, pretrained_weights: str,
                   data: str, bsz_train: int, bsz_val: int, imgsz: int,
                   conf_thres: float, iou_thres: float, cfg: str, hyp: str,
                   workers: int, selection_ratio: float = 1.0, 
                   oort_start_round: int = 0, use_random: bool = False, 
                   warmup_rounds:int = 5,
                   noise_detection_output: str = "experiments/run/local-analytics") -> None:

    
    # Register clients to Oort if used
    if server.use_oort and not use_random:
        for client in clients:
            server.oort_sampler.register_client(
                client.rank,
                client.nsamples,
                duration=2000
            )
    
    # Server initializes model
    print("Initializing model on server...")
    server.initialize_model(pretrained_weights)
    server.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)
    
    total_clients = len(clients)
    
    noisy_ranks = []
    clean_ranks = []
    detection_done = False
    print(f"[Main] Total clients = {total_clients}")
    
    print(f"[Main] Noise detection at after round {warmup_rounds - 1}")
    
    if use_random:
        print(f"[Main] Selection method: RANDOM")
        print(f"[Main] Selection ratio = {selection_ratio} ({int(total_clients * selection_ratio)} clients per round)")
        print(f"[Main] Round 0: ALL clients train {epochs} epochs to initialize weights")
    elif server.use_oort:
        print(f"[Main] Selection method: OORT")
        print(f"[Main] Oort start round: {oort_start_round}")
        print(f"[Main] Selection ratio = {selection_ratio}")
    else:
        print(f"[Main] Selection method: ALL CLIENTS")
    
    for kround in range(nrounds):
        print(f"\n{'='*50}")
        print(f"Round {kround + 1}/{nrounds}")
        print(f"{'='*50}")
        
        in_warmup = kround < warmup_rounds
        if in_warmup:
            print(f"  [WARMUP {kround + 1}/{warmup_rounds}]")
        else:
            print()
        print(f"{'='*55}")
        
        # Round 0: share initial weights with clients
        if kround == 0:
            initial_weights = server.get_weights(metadata=True)
            for client in clients:
                client.set_weights(initial_weights, metadata=True)
                client.post_init_update(data=data, cfg=cfg, hyp=hyp, imgsz=imgsz)
        
        # CLIENT SELECTION
        
        num_to_select = max(1, int(total_clients * selection_ratio))
        
        # Random selection
        if use_random and kround < 5:
            selected_clients = clients  # ALL clients
            print(f"\n[Warmup Round {kround + 1}/5] Training ALL {len(clients)} clients with {epochs} epochs")
            print(f"  Purpose: Initialize weights for future random selection")
        
       
        elif use_random:
            selected_clients = random.sample(clients, num_to_select)
            selected_ranks = [c.rank for c in selected_clients]
            print(f"\n[Random Selection] Selected {len(selected_clients)}/{total_clients} clients")
            print(f"[Random Selection] Selected client ranks: {selected_ranks}")
            
        # Oort selection
        elif server.use_oort and kround >= oort_start_round:
            feasible = [c.rank for c in clients]
            print(f"\n[Oort] round={kround} selecting num_to_select={num_to_select}")
            selected_ranks = server.oort_sampler.select_clients(
                num_clients=num_to_select,
                feasible_clients=feasible,
                round_num=kround
            )
            print(f"[Oort DEBUG] selected_ranks = {selected_ranks}")
            selected_clients = [c for c in clients if c.rank in selected_ranks]
            print(f"[Oort] Selected {len(selected_clients)}/{len(clients)} clients -> {[c.rank for c in selected_clients]}")
        
        # All clients
        else:
            selected_clients = clients
            if server.use_oort:
                print(f"\n[Oort] Warmup/start phase (round {kround}): using all clients")
        
        updates = []
        nsamples_list = []
        client_durations = []
        client_losses = []
        # client_utilities = []
        
        for client in selected_clients:
            print(f"\n--- Training Client {client.rank} ---")
            
            train_start = time.time()
            
            client.train(
                nrounds=nrounds,
                kround=kround,
                epochs=epochs,
                architecture=architecture,
                data=data,
                bsz_train=bsz_train,
                imgsz=imgsz,
                cfg=cfg,
                hyp=hyp,
                workers=workers,
                saving_path=saving_path
            )
            
            train_duration = time.time() - train_start
            client_durations.append(train_duration)
            update = client.get_update()
            updates.append(update)
            nsamples_list.append(client.nsamples)
            
            # Extract loss for Oort (if used)
            if server.use_oort and not use_random:
                try:
                    client_loss = client.extract_losses(
                        saving_path=saving_path,
                        epochs=epochs,
                        nrounds=kround 
                    )
                except Exception as e:
                    print(f"  Warning: Could not extract loss: {e}")
                    client_loss = 2.0 
                
                client_losses.append(client_loss)
                # utility = math.sqrt(max(client_loss, 1e-10)) * client.nsamples
                # client_utilities.append(utility)
                
                print(f"  Loss: {client_loss:.8f}")
                print(f"  Duration: {train_duration:.4f}s")
                print(f"  Samples: {client.nsamples}")
                # print(f"  Utility: {utility:.4f}")
                
                if kround >= oort_start_round:
                    server.oort_sampler.update_client(
                        client.rank,
                        loss=client_loss,
                        duration=train_duration,
                        round_num=kround
                    )
            else:
                print(f"  Duration: {train_duration:.4f}s")
                print(f"  Samples: {client.nsamples}")
        
        # Server aggregation
        print(f"\n--- Server Aggregation ---")
        server.aggregate(updates, nsamples_list)
        server.reparameterize(architecture)
        
        # Server evaluation
        print(f"\n--- Server Evaluation ---")
        server.test(kround, saving_path, data, bsz_val, imgsz, conf_thres, iou_thres)
        
        # Broadcast new weights to ALL clients (not just selected ones)
        new_weights = server.get_weights(metadata=False)
        for client in clients:
            client.set_weights(new_weights, metadata=False)
            
        
        last_warmup_round = warmup_rounds - 1
        if kround == last_warmup_round and not detection_done:
            print(f"\n{'#'*60}")
            print(f"  Warmup ends after round {kround + 1}.")
            print(f"  Start Noisy Client Detection...")
            print(f"{'#'*60}")
 
            noisy_ranks, clean_ranks = detect_noisy_clients(
                clients=clients,
                saving_path=saving_path,
                output_dir=noise_detection_output,
            )
            detection_done = True
 
          
            summary_path = os.path.join(noise_detection_output, "noise_detection_summary.txt")
            with open(summary_path, "w") as f:
                f.write(f"Noise detection ran after round {kround + 1} (warmup complete)\n")
                f.write(f"Noisy clients ({len(noisy_ranks)}): {noisy_ranks}\n")
                f.write(f"Clean clients ({len(clean_ranks)}): {clean_ranks}\n")
            print(f"  [OK] Summary luu t?i ? {summary_path}")
 
    # -- End: Print result noise detection --------------------------------
    if detection_done:
        print(f"\n{'='*55}")
        print("  Result Noisy Client Detection")
        print(f"{'='*55}")
        print(f"  Noisy clients: {noisy_ranks}")
        print(f"  Clean clients: {clean_ranks}")
        print(f"{'='*55}")


def gather_analytics(saving_path: str, clients: list, server=None) -> None:
    """Gather local analytics from clients; if server (with Oort) provided, save Oort utilities too."""
    os.makedirs(f'{saving_path}/run/local-analytics/', exist_ok=True)
    
    for client in clients:
        rank = client.rank
        try:
            df_lr = pd.read_csv(f'{saving_path}/run/train-client{rank}/optim_params.csv')
            df_loss = pd.read_csv(f'{saving_path}/run/train-client{rank}/training_losses.csv')
            
            df_lr.to_csv(f'{saving_path}/run/local-analytics/optim_params_{rank}.csv', index=False)
            df_loss.to_csv(f'{saving_path}/run/local-analytics/training_losses_{rank}.csv', index=False)
            
            if os.path.exists(f'{saving_path}/run/train-client{rank}/opt.yaml'):
                with open(f'{saving_path}/run/train-client{rank}/opt.yaml') as f:
                    save_yaml = yaml.load(f, Loader=yaml.SafeLoader)
                with open(f'{saving_path}/run/local-analytics/opt_{rank}.yaml', 'w') as f:
                    yaml.dump(save_yaml, f)
        except Exception as e:
            print(f"Warning: Could not gather analytics for client {rank}: {e}")
    
    # Save Oort utilities if server provided
    if server is not None and getattr(server, 'use_oort', False) and hasattr(server, 'oort_sampler'):
        try:
            utilities = {}
            for client_id, info in server.oort_sampler.selector.totalArms.items():
                utilities[client_id] = {
                    'reward': info.get('reward', 0.0),
                    'duration': info.get('duration', 0.0),
                    'count': info.get('count', 0),
                    'last_selected_round': info.get('time_stamp', -1)
                }
            df_util = pd.DataFrame.from_dict(utilities, orient='index')
            df_util.to_csv(f'{saving_path}/run/local-analytics/oort_utilities.csv')
            print(f"[INFO] Oort utilities saved for {len(utilities)} clients.")
            
            server.oort_sampler.selector.export_utility_pivot(
                f'{saving_path}/run/local-analytics/client_utilities_pivot.csv'
            )
            print(f"[INFO] Oort utility pivot CSV exported.")
            
        except Exception as e:
            print(f"Warning: Could not gather Oort utilities: {e}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--nrounds', type=int, default=30, help='number of communication rounds')
    parser.add_argument('--epochs', type=int, default=5, help='number of epochs per round')
    parser.add_argument('--server-opt', type=str, default='fedavg', help='aggregation algorithm')
    parser.add_argument('--server-lr', type=float, default=1., help='server learning rate')
    parser.add_argument('--tau', type=float, default=1e-3, help='server adaptivity')
    parser.add_argument('--beta', type=float, default=0.1, help='server momentum')
    parser.add_argument('--architecture', type=str, default='yolov7', help='model architecture')
    parser.add_argument('--weights', type=str, required=True, help='path to pretrained weights')
    parser.add_argument('--data', type=str, required=True, help='*.yaml path')
    parser.add_argument('--bsz-train', type=int, default=16, help='batch size for training')
    parser.add_argument('--bsz-val', type=int, default=16, help='batch size for evaluation')
    parser.add_argument('--img', type=int, default=640, help='image size')
    parser.add_argument('--conf', type=float, default=0.001, help='confidence threshold')
    parser.add_argument('--iou', type=float, default=0.65, help='IOU threshold for NMS')
    parser.add_argument('--cfg', type=str, default='yolov7/cfg/training/yolov7.yaml', help='model.yaml path')
    parser.add_argument('--hyp', type=str, required=True, help='hyperparameters path')
    parser.add_argument('--workers', type=int, default=4, help='number of workers')
    
    # ===== CLIENT SELECTION PARAMETERS =====
    parser.add_argument('--use-random', action='store_true', 
                        help='Use RANDOM client selection instead of Oort')
    parser.add_argument('--use-oort', action='store_true', 
                        help='Enable Oort client selection')
    parser.add_argument('--selection-ratio', type=float, default=1.0, 
                        help='Fraction of clients to select each round (0.0-1.0)')
    parser.add_argument('--oort-start-round', type=int, default=1, 
                        help='Round index to start Oort client selection (if using Oort)')
    parser.add_argument(
        "--warmup-rounds", type=int, default=5,
        help="Number of round warmup before noise detection (default: 5)"
    )
    parser.add_argument(
        "--noise-output", type=str, default=None,
        help="Save noise detection results(default: experiments/run/local-analytics)"
    )
    
    args = parser.parse_args()
    
    # Set random seed for reproducibility
    random.seed(42)
    
    # Validation
    if args.use_random and args.use_oort:
        raise ValueError("Cannot use both --use-random and --use-oort at the same time")
    
    # Initialize server
    print("Initializing server...")
    server = Server(args.server_opt, args.server_lr, args.tau, args.beta, 
                   use_oort=args.use_oort and not args.use_random)
    server.get_device_info()
    
    # Initialize clients: detect from dataset folder
    print("Detecting clients from dataset folder...")
    with open(args.data) as f:
        data_dict = yaml.load(f, Loader=yaml.SafeLoader)
    
    train_root = data_dict.get('train')
    if train_root is None:
        raise RuntimeError("data yaml must contain 'train' path (where client subfolders are).")
    
    client_dirs = sorted([d for d in os.listdir(train_root) if d.startswith("client")])
    clients = []
    
    for idx, dirname in enumerate(client_dirs, start=1):
        client = Client(rank=idx)
        client.get_device_info()
        img_path = os.path.join(train_root, dirname, "images")
        try:
            client.nsamples = len(os.listdir(img_path))
        except Exception:
            client.nsamples = 1
        clients.append(client)
    
    print(f"Detected {len(clients)} clients from {train_root}.")
    
    # Validate selection ratio
    if not 0.0 < args.selection_ratio <= 1.0:
        raise ValueError(f"selection_ratio must be in (0.0, 1.0], got {args.selection_ratio}")
    
    # Create saving folder
    saving_path = 'experiments'
    os.makedirs(saving_path, exist_ok=True)
    os.makedirs(f'{saving_path}/weights/', exist_ok=True)
    os.makedirs(f'{saving_path}/run/', exist_ok=True)
    
 
    
    noise_output = args.noise_output or f"{saving_path}/run/local-analytics"
    # Determine selection method
    if args.use_random:
        selection_method = 'random'
    elif args.use_oort:
        selection_method = 'oort'
    else:
        selection_method = 'all_clients'
    
    # Save configuration
    with open(f'{saving_path}/config.txt', 'w') as f:
        f.write(f'nrounds: {args.nrounds}\n')
        f.write(f'epochs: {args.epochs}\n')
        f.write(f'total_clients: {len(clients)}\n')
        f.write(f'selection_method: {selection_method}\n')
        f.write(f'selection_ratio: {args.selection_ratio}\n')
        f.write(f'clients_per_round: {max(1, int(len(clients) * args.selection_ratio))}\n')
        if args.use_oort:
            f.write(f'oort_start_round: {args.oort_start_round}\n')
        f.write(f'server opt: {args.server_opt}\n')
        f.write(f'server learning rate: {args.server_lr}\n')
        if args.server_opt == 'fedavgm':
            f.write(f'beta: {args.beta}\n')
        if args.server_opt in ['fedadagrad', 'fedadam', 'fedyogi']:
            f.write(f'tau: {args.tau}\n')
        f.write(f'architecture: {args.architecture}\n')
        f.write(f'weights: {args.weights}\n')
        f.write(f'data: {args.data}\n')
        f.write(f'batch size (train): {args.bsz_train}\n')
        f.write(f'batch size (eval): {args.bsz_val}\n')
        f.write(f'img: {args.img}\n')
        f.write(f'cfg: {args.cfg}\n')
        f.write(f'hyp: {args.hyp}\n')
    
    try:
        shutil.copy(args.cfg, saving_path)
        shutil.copy(args.hyp, saving_path)
        shutil.copy(args.data, saving_path)
    except Exception as e:
        print(f"Warning: Could not copy config files: {e}")
    
    # Run federated learning
    print("\n" + "="*60)
    if args.use_random:
        print("Starting Federated Learning with RANDOM CLIENT SELECTION")
    elif args.use_oort:
        print("Starting Federated Learning with OORT CLIENT SELECTION")
    else:
        print("Starting Federated Learning with ALL CLIENTS")
    print(f"Total clients: {len(clients)}")
    print(f"Selection ratio: {args.selection_ratio}")
    print(f"Clients per round: {max(1, int(len(clients) * args.selection_ratio))}")
    print("="*60 + "\n")
    
    federated_loop(
        server=server,
        clients=clients,
        nrounds=args.nrounds,
        epochs=args.epochs,
        saving_path=saving_path,
        architecture=args.architecture,
        pretrained_weights=args.weights,
        data=args.data,
        bsz_train=args.bsz_train,
        bsz_val=args.bsz_val,
        imgsz=args.img,
        conf_thres=args.conf,
        iou_thres=args.iou,
        cfg=args.cfg,
        hyp=args.hyp,
        workers=args.workers,
        selection_ratio=args.selection_ratio,
        oort_start_round=args.oort_start_round,
        use_random=args.use_random,
        warmup_rounds=args.warmup_rounds,
        noise_detection_output=noise_output
    )
    
    # Gather analytics (and save Oort utilities if used)
    print("\nGathering analytics...")
    gather_analytics(saving_path, clients, server=server)
    
    print("\nFederated learning completed!")